version: '3.8'

services:
  rpc-proxy:
    build: .  # Build จาก Dockerfile ในโฟลเดอร์นี้
    ports:
      - "8888:8888"
    environment:
      # Server Configuration
      - SERVER_PORT=8888
      
      # ปิดการใช้ database โดยตั้ง DB_HOST เป็น empty string
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      
      # Ethereum Mainnet
      - ETHEREUM_RPC_ENDPOINTS=https://eth.llamarpc.com,https://ethereum.publicnode.com,https://rpc.ankr.com/eth
      
      # Sepolia Testnet  
      - SEPOLIA_RPC_ENDPOINTS=https://sepolia.drpc.org,https://ethereum-sepolia-rpc.publicnode.com,https://rpc.ankr.com/eth_sepolia
      
      # Soneium Mainnet
      - SONEIUM_RPC_ENDPOINTS=https://soneium.drpc.org,https://rpc.soneium.org
      
      # เพิ่ม Chain อื่นๆ ตามต้องการ
      # - POLYGON_RPC_ENDPOINTS=https://polygon-rpc.com,https://rpc-mainnet.matic.network
      # - ARBITRUM_RPC_ENDPOINTS=https://arb1.arbitrum.io/rpc
      
      # Health Check Settings
      - HEALTH_CHECK_INTERVAL=30s
      - HEALTH_CHECK_TIMEOUT=5s
      
      # Proxy Settings
      - PROXY_TIMEOUT=10s
      - LOG_LEVEL=info
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s